// <auto-generated />
using System;
using MensaWebAPI.Models.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MensaWebAPI.Migrations
{
    [DbContext(typeof(MenuContext))]
    [Migration("20231229093057_FK")]
    partial class FK
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MensaAppKlassenBibliothek.Menu", b =>
                {
                    b.Property<int>("MenuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("MainCourse")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Starter")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("WhichMenu")
                        .HasColumnType("int");

                    b.HasKey("MenuId");

                    b.ToTable("Menues");
                });

            modelBuilder.Entity("MensaAppKlassenBibliothek.MenuPerson", b =>
                {
                    b.Property<int>("MenuPersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Activated")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("InShoppingcart")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateOnly>("OrderDate")
                        .HasColumnType("date");

                    b.Property<bool>("Payed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("menuId")
                        .HasColumnType("int");

                    b.HasKey("MenuPersonId");

                    b.HasIndex("email");

                    b.HasIndex("menuId");

                    b.ToTable("MenuPersons");
                });

            modelBuilder.Entity("MensaAppKlassenBibliothek.Person", b =>
                {
                    b.Property<string>("Email")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Email");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("MensaAppKlassenBibliothek.MenuPerson", b =>
                {
                    b.HasOne("MensaAppKlassenBibliothek.Person", "Person")
                        .WithMany("MenuPersons")
                        .HasForeignKey("email")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MensaAppKlassenBibliothek.Menu", "Menu")
                        .WithMany("MenuPersons")
                        .HasForeignKey("menuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Menu");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("MensaAppKlassenBibliothek.Menu", b =>
                {
                    b.Navigation("MenuPersons");
                });

            modelBuilder.Entity("MensaAppKlassenBibliothek.Person", b =>
                {
                    b.Navigation("MenuPersons");
                });
#pragma warning restore 612, 618
        }
    }
}
