// <auto-generated />
using System;
using MensaWebsite.Models.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MensaWebsite.Migrations
{
    [DbContext(typeof(MenuContext))]
    partial class MenuContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MensaAppKlassenBibliothek.Menu", b =>
                {
                    b.Property<int>("MenuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("MainCourse")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PricesPriceId")
                        .HasColumnType("int");

                    b.Property<string>("Starter")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("MenuId");

                    b.HasIndex("PricesPriceId");

                    b.ToTable("Menues");
                });

            modelBuilder.Entity("MensaAppKlassenBibliothek.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateOnly>("OrderDate")
                        .HasColumnType("date");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("OrderId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("MensaAppKlassenBibliothek.PriceForMenu", b =>
                {
                    b.Property<int>("PriceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("PriceStudent")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("PriceTeacher")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("PriceId");

                    b.ToTable("Prices");
                });

            modelBuilder.Entity("MenuOrder", b =>
                {
                    b.Property<int>("MenusMenuId")
                        .HasColumnType("int");

                    b.Property<int>("OrdersOrderId")
                        .HasColumnType("int");

                    b.HasKey("MenusMenuId", "OrdersOrderId");

                    b.HasIndex("OrdersOrderId");

                    b.ToTable("MenuOrder");
                });

            modelBuilder.Entity("MensaAppKlassenBibliothek.Menu", b =>
                {
                    b.HasOne("MensaAppKlassenBibliothek.PriceForMenu", "Prices")
                        .WithMany()
                        .HasForeignKey("PricesPriceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prices");
                });

            modelBuilder.Entity("MenuOrder", b =>
                {
                    b.HasOne("MensaAppKlassenBibliothek.Menu", null)
                        .WithMany()
                        .HasForeignKey("MenusMenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MensaAppKlassenBibliothek.Order", null)
                        .WithMany()
                        .HasForeignKey("OrdersOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
